### ISSUE TITLE
Support Windows on ARM64 (using Void Linux aarch64)

### ISSUE THREAD

**Issue by rubin55** [am11/VoidWSL#12]
Can you also support Windows on ARM64? There seem to be tar releases for Void on ARM64 (aarch64) and WSL works on Windows on ARM64 too.

**Comment by am11** [comment]
@rubin55, I have released a [new version](https://github.com/am11/VoidWSL/releases/tag/22111400) with arm64 artifacts:

glibc: `void-aarch64.zip`
musl-libc: `void-aarch64-musl.zip`

**Comment by rubin55** [comment]
I immediately tried the installer, both on X86_64 and AARCH64 (my Surface Pro X).

On X86_64 Windows 10, the install finished succesfully. On my Surface Pro X Windows 11 I got:

```
Using C:\Users\rubin\downloads\rootfs.tar.gz
Installing...
ERR: The operation could not be started because a required feature is not installed.
HRESULT: 0x80370114
```

This system is already running WSL (a standard Debian aarch64 WSL1) so I don't think I'm missing any Windows features to support running WSL..

**Comment by rubin55** [comment]
I searched for the hex code and found this: https://github.com/microsoft/WSL/issues/8430#issuecomment-1308947642

I followed the steps there to fully enable Hyper-V and can confirm installation finished without issues!

Extreme kudos for the fast response, it is extremely, extremely much appreciated. You definitely improved my workflow by a mile or two. Thanks a lot.
