### ISSUE TITLE
WSLg Support?

### ISSUE THREAD

**Issue by StellarOrbit** [am11/VoidWSL#7]
Hello, I was wondering if there is a possibility of having support for gui programs in void wsl? Apparently there is packages that are needed, but it's hard to find technical information regarding this. If it isn't possible, then it's fine, but I am really curious if it is possible.

**Comment by am11** [comment]
Hi, thanks for opening this issue. TBH, I am not a GUI expert, so I will defer to others' answers. Skimming though https://github.com/microsoft/wslg/blob/main/README.md, I think VoidWSL and VoidMuslWSL should be supported out of the box on WSLg, like any other WSLg compatible distro. i.e. we don't need to install anything extra in userland for GUI apps.

> ### Pre-requisites
> Windows 11 (build 22000.*) or Windows 11 Insider Preview (builds 21362+)

if you have met the aforementioned WSLg prerequisites (and you are able to run, e.g. Ubuntu GUI apps) you can install the GUI apps on Void Linux via xbps-install command, and launch them on Windows environment.

ps - these days I am primarily using Ubuntu Desktop on bare metal, so I don't often get to test WSL latest releases.

**Comment by StellarOrbit** [comment]
> Hi, thanks for opening this issue. TBH, I am not a GUI expert, so I will defer to others' answers. Skimming thought https://github.com/microsoft/wslg/blob/main/README.md, I think VoidWSL and VoidMuslWSL should be supported out of the box on WSLg, like any other WSLg compatible distro. i.e. we don't need to install anything extra in userland for GUI apps.
> 
> > ### Pre-requisites
> > Windows 11 (build 22000.*) or Windows 11 Insider Preview (builds 21362+)
> 
> if you have met the aforementioned WSLg prerequisites (and you are able to run, e.g. Ubuntu GUI apps) you can install the GUI apps on Void Linux via xbps-install command, and launch them on Windows environment.
> 
> ps - these days I am primarily using Ubuntu Desktop on bare metal, so I don't often get to test WSL latest releases.

That's fair. I have installed gedit as a test to see if it was gonna work last night, and it was seg faulting after saying it couldn't do anything with dconf

```
`(gedit:286): dconf-WARNING **: 12:30:25.146: failed to commit changes to dconf: Cannot spawn a message bus without a machine-id: Unable to load /var/lib/dbus/machine-id or /etc/machine-id: Failed to open file “/var/lib/dbus/machine-id”: No such file or directory

(gedit:286): dconf-WARNING **: 12:30:25.150: failed to commit changes to dconf: Cannot spawn a message bus without a machine-id: Unable to load /var/lib/dbus/machine-id or /etc/machine-id: Failed to open file “/var/lib/dbus/machine-id”: No such file or directory

(gedit:286): Gdk-CRITICAL **: 12:30:25.264: ../gdk/wayland/gdkdisplay-wayland.c:1399: Unable to create Cairo image surface: invalid value (typically too big) for the size of the input (surface, pattern, etc.)
Segmentation fault`
```

Which lead me to think that this isn't working just yet, and it seems that Ubuntu WSL seems to have some specific wsl packages, but I am unsure.

**Comment by am11** [comment]
Could you run `export` in that Ubuntu instance (where you are able to successfully launch the GUI app) and Void instance (where it is failing) and compare to find whether the value of `DISPLAY` is matching? It should be `:0` (colon, followed by zero) in the working instance.

**Comment by StellarOrbit** [comment]
> Could you run `export` in that Ubuntu instance (where you are able to successfully launch the GUI app) and Void instance (where it is failing) and compare to find whether the value of `DISPLAY` is matching? It should be `:0` (colon, followed by zero) in the working instance.

You are right. It works. I just installed mpv in void wsl and it works just fine. I am going to close the issue. I appreciate your help.
